# Generated by Django 3.2.16 on 2023-12-15 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='podcastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(max_length=2500)),
                ('date_created', models.DateTimeField()),
                ('date_finished', models.DateTimeField()),
                ('state', models.BooleanField(default=True)),
                ('flag', models.CharField(choices=[('b', 'blank'), ('bl', 'blue'), ('r', 'red'), ('g', 'green'), ('y', 'yellow')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userPodcastPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_pool', models.ManyToManyField(to='home.podcastCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='taskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('tasks', models.ManyToManyField(to='home.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='liste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tasklist'),
        ),
        migrations.CreateModel(
            name='podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.podcastcategory')),
            ],
        ),
    ]
