# Generated by Django 3.2.16 on 2023-12-15 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tasklist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='liste',
            new_name='owner',
        ),
    ]
