# Generated by Django 3.2.16 on 2023-12-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_liste_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='home.task'),
        ),
    ]
